# 配置数据库连接
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: yanyuqinghe
    initialSize: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true

# 配置mybatis
mybatis:
  # mapper文件路径
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true
  # POJO扫描包
  type-aliases-package: com.springboot.demo.pojo
  configuration:
    map-underscore-to-camel-case: true

# 分页插件
pagehelper:
  autoDialect: true
  closeConn: false
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
  row-bounds-with-count: true

# 打印sql日志
logging:
  level:
    com.springboot.demo: debug

# 修改服务器端口
server:
  port: 8090
